// Code generated by ent, DO NOT EDIT.

package examples

import (
	"time"

	"github.com/uniteweb/entkit/examples/schema"
	"github.com/uniteweb/entkit/examples/user"
	"github.com/uniteweb/entkit/examples/userversion"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescDeletedAt is the schema descriptor for deleted_at field.
	userDescDeletedAt := userMixinFields0[0].Descriptor()
	// user.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	user.DefaultDeletedAt = userDescDeletedAt.Default.(time.Time)
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[1].Descriptor()
	// user.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	user.AgeValidator = userDescAge.Validators[0].(func(int) error)
	userversionMixin := schema.UserVersion{}.Mixin()
	userversionMixinFields0 := userversionMixin[0].Fields()
	_ = userversionMixinFields0
	userversionFields := schema.UserVersion{}.Fields()
	_ = userversionFields
	// userversionDescVersion is the schema descriptor for version field.
	userversionDescVersion := userversionMixinFields0[0].Descriptor()
	// userversion.DefaultVersion holds the default value on creation for the version field.
	userversion.DefaultVersion = userversionDescVersion.Default.(int)
	// userversion.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	userversion.VersionValidator = userversionDescVersion.Validators[0].(func(int) error)
	// userversionDescAge is the schema descriptor for age field.
	userversionDescAge := userversionFields[1].Descriptor()
	// userversion.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	userversion.AgeValidator = userversionDescAge.Validators[0].(func(int) error)
}
