// Code generated by ent, DO NOT EDIT.

package examples

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/uniteweb/entkit/examples/predicate"
	"github.com/uniteweb/entkit/examples/userversion"
)

// UserVersionDelete is the builder for deleting a UserVersion entity.
type UserVersionDelete struct {
	config
	hooks    []Hook
	mutation *UserVersionMutation
}

// Where appends a list predicates to the UserVersionDelete builder.
func (uvd *UserVersionDelete) Where(ps ...predicate.UserVersion) *UserVersionDelete {
	uvd.mutation.Where(ps...)
	return uvd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uvd *UserVersionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, uvd.sqlExec, uvd.mutation, uvd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (uvd *UserVersionDelete) ExecX(ctx context.Context) int {
	n, err := uvd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uvd *UserVersionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userversion.Table, sqlgraph.NewFieldSpec(userversion.FieldID, field.TypeInt))
	if ps := uvd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, uvd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	uvd.mutation.done = true
	return affected, err
}

// UserVersionDeleteOne is the builder for deleting a single UserVersion entity.
type UserVersionDeleteOne struct {
	uvd *UserVersionDelete
}

// Where appends a list predicates to the UserVersionDelete builder.
func (uvdo *UserVersionDeleteOne) Where(ps ...predicate.UserVersion) *UserVersionDeleteOne {
	uvdo.uvd.mutation.Where(ps...)
	return uvdo
}

// Exec executes the deletion query.
func (uvdo *UserVersionDeleteOne) Exec(ctx context.Context) error {
	n, err := uvdo.uvd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userversion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uvdo *UserVersionDeleteOne) ExecX(ctx context.Context) {
	if err := uvdo.Exec(ctx); err != nil {
		panic(err)
	}
}
