// Code generated by ent, DO NOT EDIT.

package examples

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/uniteweb/entkit/examples/userversion"
)

// UserVersionCreate is the builder for creating a UserVersion entity.
type UserVersionCreate struct {
	config
	mutation *UserVersionMutation
	hooks    []Hook
}

// SetVersion sets the "version" field.
func (uvc *UserVersionCreate) SetVersion(i int) *UserVersionCreate {
	uvc.mutation.SetVersion(i)
	return uvc
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (uvc *UserVersionCreate) SetNillableVersion(i *int) *UserVersionCreate {
	if i != nil {
		uvc.SetVersion(*i)
	}
	return uvc
}

// SetName sets the "name" field.
func (uvc *UserVersionCreate) SetName(s string) *UserVersionCreate {
	uvc.mutation.SetName(s)
	return uvc
}

// SetAge sets the "age" field.
func (uvc *UserVersionCreate) SetAge(i int) *UserVersionCreate {
	uvc.mutation.SetAge(i)
	return uvc
}

// Mutation returns the UserVersionMutation object of the builder.
func (uvc *UserVersionCreate) Mutation() *UserVersionMutation {
	return uvc.mutation
}

// Save creates the UserVersion in the database.
func (uvc *UserVersionCreate) Save(ctx context.Context) (*UserVersion, error) {
	uvc.defaults()
	return withHooks(ctx, uvc.sqlSave, uvc.mutation, uvc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uvc *UserVersionCreate) SaveX(ctx context.Context) *UserVersion {
	v, err := uvc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uvc *UserVersionCreate) Exec(ctx context.Context) error {
	_, err := uvc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uvc *UserVersionCreate) ExecX(ctx context.Context) {
	if err := uvc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uvc *UserVersionCreate) defaults() {
	if _, ok := uvc.mutation.Version(); !ok {
		v := userversion.DefaultVersion
		uvc.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uvc *UserVersionCreate) check() error {
	if _, ok := uvc.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`examples: missing required field "UserVersion.version"`)}
	}
	if v, ok := uvc.mutation.Version(); ok {
		if err := userversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`examples: validator failed for field "UserVersion.version": %w`, err)}
		}
	}
	if _, ok := uvc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`examples: missing required field "UserVersion.name"`)}
	}
	if _, ok := uvc.mutation.Age(); !ok {
		return &ValidationError{Name: "age", err: errors.New(`examples: missing required field "UserVersion.age"`)}
	}
	if v, ok := uvc.mutation.Age(); ok {
		if err := userversion.AgeValidator(v); err != nil {
			return &ValidationError{Name: "age", err: fmt.Errorf(`examples: validator failed for field "UserVersion.age": %w`, err)}
		}
	}
	return nil
}

func (uvc *UserVersionCreate) sqlSave(ctx context.Context) (*UserVersion, error) {
	if err := uvc.check(); err != nil {
		return nil, err
	}
	_node, _spec := uvc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uvc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	uvc.mutation.id = &_node.ID
	uvc.mutation.done = true
	return _node, nil
}

func (uvc *UserVersionCreate) createSpec() (*UserVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &UserVersion{config: uvc.config}
		_spec = sqlgraph.NewCreateSpec(userversion.Table, sqlgraph.NewFieldSpec(userversion.FieldID, field.TypeInt))
	)
	if value, ok := uvc.mutation.Version(); ok {
		_spec.SetField(userversion.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := uvc.mutation.Name(); ok {
		_spec.SetField(userversion.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := uvc.mutation.Age(); ok {
		_spec.SetField(userversion.FieldAge, field.TypeInt, value)
		_node.Age = value
	}
	return _node, _spec
}

// UserVersionCreateBulk is the builder for creating many UserVersion entities in bulk.
type UserVersionCreateBulk struct {
	config
	err      error
	builders []*UserVersionCreate
}

// Save creates the UserVersion entities in the database.
func (uvcb *UserVersionCreateBulk) Save(ctx context.Context) ([]*UserVersion, error) {
	if uvcb.err != nil {
		return nil, uvcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(uvcb.builders))
	nodes := make([]*UserVersion, len(uvcb.builders))
	mutators := make([]Mutator, len(uvcb.builders))
	for i := range uvcb.builders {
		func(i int, root context.Context) {
			builder := uvcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uvcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uvcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uvcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uvcb *UserVersionCreateBulk) SaveX(ctx context.Context) []*UserVersion {
	v, err := uvcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uvcb *UserVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := uvcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uvcb *UserVersionCreateBulk) ExecX(ctx context.Context) {
	if err := uvcb.Exec(ctx); err != nil {
		panic(err)
	}
}
