// Code generated by ent, DO NOT EDIT.

package examples

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/uniteweb/entkit/examples/predicate"
	"github.com/uniteweb/entkit/examples/userversion"
)

// UserVersionQuery is the builder for querying UserVersion entities.
type UserVersionQuery struct {
	config
	ctx        *QueryContext
	order      []userversion.OrderOption
	inters     []Interceptor
	predicates []predicate.UserVersion
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserVersionQuery builder.
func (uvq *UserVersionQuery) Where(ps ...predicate.UserVersion) *UserVersionQuery {
	uvq.predicates = append(uvq.predicates, ps...)
	return uvq
}

// Limit the number of records to be returned by this query.
func (uvq *UserVersionQuery) Limit(limit int) *UserVersionQuery {
	uvq.ctx.Limit = &limit
	return uvq
}

// Offset to start from.
func (uvq *UserVersionQuery) Offset(offset int) *UserVersionQuery {
	uvq.ctx.Offset = &offset
	return uvq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uvq *UserVersionQuery) Unique(unique bool) *UserVersionQuery {
	uvq.ctx.Unique = &unique
	return uvq
}

// Order specifies how the records should be ordered.
func (uvq *UserVersionQuery) Order(o ...userversion.OrderOption) *UserVersionQuery {
	uvq.order = append(uvq.order, o...)
	return uvq
}

// First returns the first UserVersion entity from the query.
// Returns a *NotFoundError when no UserVersion was found.
func (uvq *UserVersionQuery) First(ctx context.Context) (*UserVersion, error) {
	nodes, err := uvq.Limit(1).All(setContextOp(ctx, uvq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userversion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uvq *UserVersionQuery) FirstX(ctx context.Context) *UserVersion {
	node, err := uvq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserVersion ID from the query.
// Returns a *NotFoundError when no UserVersion ID was found.
func (uvq *UserVersionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uvq.Limit(1).IDs(setContextOp(ctx, uvq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userversion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uvq *UserVersionQuery) FirstIDX(ctx context.Context) int {
	id, err := uvq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserVersion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserVersion entity is found.
// Returns a *NotFoundError when no UserVersion entities are found.
func (uvq *UserVersionQuery) Only(ctx context.Context) (*UserVersion, error) {
	nodes, err := uvq.Limit(2).All(setContextOp(ctx, uvq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userversion.Label}
	default:
		return nil, &NotSingularError{userversion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uvq *UserVersionQuery) OnlyX(ctx context.Context) *UserVersion {
	node, err := uvq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserVersion ID in the query.
// Returns a *NotSingularError when more than one UserVersion ID is found.
// Returns a *NotFoundError when no entities are found.
func (uvq *UserVersionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uvq.Limit(2).IDs(setContextOp(ctx, uvq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userversion.Label}
	default:
		err = &NotSingularError{userversion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uvq *UserVersionQuery) OnlyIDX(ctx context.Context) int {
	id, err := uvq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserVersions.
func (uvq *UserVersionQuery) All(ctx context.Context) ([]*UserVersion, error) {
	ctx = setContextOp(ctx, uvq.ctx, ent.OpQueryAll)
	if err := uvq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserVersion, *UserVersionQuery]()
	return withInterceptors[[]*UserVersion](ctx, uvq, qr, uvq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uvq *UserVersionQuery) AllX(ctx context.Context) []*UserVersion {
	nodes, err := uvq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserVersion IDs.
func (uvq *UserVersionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if uvq.ctx.Unique == nil && uvq.path != nil {
		uvq.Unique(true)
	}
	ctx = setContextOp(ctx, uvq.ctx, ent.OpQueryIDs)
	if err = uvq.Select(userversion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uvq *UserVersionQuery) IDsX(ctx context.Context) []int {
	ids, err := uvq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uvq *UserVersionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uvq.ctx, ent.OpQueryCount)
	if err := uvq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uvq, querierCount[*UserVersionQuery](), uvq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uvq *UserVersionQuery) CountX(ctx context.Context) int {
	count, err := uvq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uvq *UserVersionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uvq.ctx, ent.OpQueryExist)
	switch _, err := uvq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("examples: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uvq *UserVersionQuery) ExistX(ctx context.Context) bool {
	exist, err := uvq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserVersionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uvq *UserVersionQuery) Clone() *UserVersionQuery {
	if uvq == nil {
		return nil
	}
	return &UserVersionQuery{
		config:     uvq.config,
		ctx:        uvq.ctx.Clone(),
		order:      append([]userversion.OrderOption{}, uvq.order...),
		inters:     append([]Interceptor{}, uvq.inters...),
		predicates: append([]predicate.UserVersion{}, uvq.predicates...),
		// clone intermediate query.
		sql:  uvq.sql.Clone(),
		path: uvq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Version int `json:"version,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserVersion.Query().
//		GroupBy(userversion.FieldVersion).
//		Aggregate(examples.Count()).
//		Scan(ctx, &v)
func (uvq *UserVersionQuery) GroupBy(field string, fields ...string) *UserVersionGroupBy {
	uvq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserVersionGroupBy{build: uvq}
	grbuild.flds = &uvq.ctx.Fields
	grbuild.label = userversion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Version int `json:"version,omitempty"`
//	}
//
//	client.UserVersion.Query().
//		Select(userversion.FieldVersion).
//		Scan(ctx, &v)
func (uvq *UserVersionQuery) Select(fields ...string) *UserVersionSelect {
	uvq.ctx.Fields = append(uvq.ctx.Fields, fields...)
	sbuild := &UserVersionSelect{UserVersionQuery: uvq}
	sbuild.label = userversion.Label
	sbuild.flds, sbuild.scan = &uvq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserVersionSelect configured with the given aggregations.
func (uvq *UserVersionQuery) Aggregate(fns ...AggregateFunc) *UserVersionSelect {
	return uvq.Select().Aggregate(fns...)
}

func (uvq *UserVersionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uvq.inters {
		if inter == nil {
			return fmt.Errorf("examples: uninitialized interceptor (forgotten import examples/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uvq); err != nil {
				return err
			}
		}
	}
	for _, f := range uvq.ctx.Fields {
		if !userversion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("examples: invalid field %q for query", f)}
		}
	}
	if uvq.path != nil {
		prev, err := uvq.path(ctx)
		if err != nil {
			return err
		}
		uvq.sql = prev
	}
	return nil
}

func (uvq *UserVersionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserVersion, error) {
	var (
		nodes = []*UserVersion{}
		_spec = uvq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserVersion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserVersion{config: uvq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uvq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uvq *UserVersionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uvq.querySpec()
	_spec.Node.Columns = uvq.ctx.Fields
	if len(uvq.ctx.Fields) > 0 {
		_spec.Unique = uvq.ctx.Unique != nil && *uvq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, uvq.driver, _spec)
}

func (uvq *UserVersionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userversion.Table, userversion.Columns, sqlgraph.NewFieldSpec(userversion.FieldID, field.TypeInt))
	_spec.From = uvq.sql
	if unique := uvq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uvq.path != nil {
		_spec.Unique = true
	}
	if fields := uvq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userversion.FieldID)
		for i := range fields {
			if fields[i] != userversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uvq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uvq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uvq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uvq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uvq *UserVersionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uvq.driver.Dialect())
	t1 := builder.Table(userversion.Table)
	columns := uvq.ctx.Fields
	if len(columns) == 0 {
		columns = userversion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uvq.sql != nil {
		selector = uvq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uvq.ctx.Unique != nil && *uvq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range uvq.predicates {
		p(selector)
	}
	for _, p := range uvq.order {
		p(selector)
	}
	if offset := uvq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uvq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserVersionGroupBy is the group-by builder for UserVersion entities.
type UserVersionGroupBy struct {
	selector
	build *UserVersionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uvgb *UserVersionGroupBy) Aggregate(fns ...AggregateFunc) *UserVersionGroupBy {
	uvgb.fns = append(uvgb.fns, fns...)
	return uvgb
}

// Scan applies the selector query and scans the result into the given value.
func (uvgb *UserVersionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uvgb.build.ctx, ent.OpQueryGroupBy)
	if err := uvgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserVersionQuery, *UserVersionGroupBy](ctx, uvgb.build, uvgb, uvgb.build.inters, v)
}

func (uvgb *UserVersionGroupBy) sqlScan(ctx context.Context, root *UserVersionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uvgb.fns))
	for _, fn := range uvgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uvgb.flds)+len(uvgb.fns))
		for _, f := range *uvgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uvgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uvgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserVersionSelect is the builder for selecting fields of UserVersion entities.
type UserVersionSelect struct {
	*UserVersionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uvs *UserVersionSelect) Aggregate(fns ...AggregateFunc) *UserVersionSelect {
	uvs.fns = append(uvs.fns, fns...)
	return uvs
}

// Scan applies the selector query and scans the result into the given value.
func (uvs *UserVersionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uvs.ctx, ent.OpQuerySelect)
	if err := uvs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserVersionQuery, *UserVersionSelect](ctx, uvs.UserVersionQuery, uvs, uvs.inters, v)
}

func (uvs *UserVersionSelect) sqlScan(ctx context.Context, root *UserVersionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uvs.fns))
	for _, fn := range uvs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uvs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uvs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
