// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserVersion is the predicate function for userversion builders.
type UserVersion func(*sql.Selector)
